name: NewPlugin
version: 1.0
author: MrDark57_
main: mrdark57.newplugin.Main
commands:
  kit:
    description: Give you a simple kit
    usage: /<command>
  newplugin:
    description: The main command
    usage: /<command>
#    permission: yourplugin.yourcommandpermission